#!/bin/sh

exec sfdisk -d /dev/sda | awk -v p='1 2 4 3 5 6' 'BEGIN { i=1; n=split(p,pp," "); } { if(NF > 2) l[i++] = $0; else print $0 } END { for(j=1; j<n; j++) print "x " l[pp[j]] }'  | sfdisk /dev/sda
